// =============================================================
// NORAYA — Conteúdo do site (PORTUGUÊS DE PORTUGAL)
// =============================================================

export const brand = {
  name: "NORAYA",
  tagline: "PERFUMES ÁRABES",
  logo: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/dqwqzxom_ChatGPT%20Image%2012_05_2026%2C%2019_31_54.png",
  instagram: "@noraya.perfumes",
};

export const nav = [
  { label: "VER TUDO", href: "#tudo" },
  { label: "NOVIDADES", href: "#novidades" },
  { label: "MAIS VENDIDOS", href: "#mais-vendidos" },
  { label: "PARA ELA", href: "#femininos" },
  { label: "PARA ELE", href: "#masculinos" },
  { label: "UNISSEX", href: "#tudo" },
];

export const hero = {
  kicker: "LANÇAMENTOS",
  titleLine1: "Asad",
  titleItalic: "Lattafa",
  description: "Sinta o poder. Notas amadeiradas, especiarias intensas e um rastro marcante que dura até 12 horas.",
  cta: "Comprar",
  background: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/ielqruif_ChatGPT%20Image%2012_05_2026%2C%2020_47_33.png",
};

export const bestSellers = {
  kicker: "ESSENCIAIS",
  titleLine1: "Mais",
  titleItalic: "vendidos",
  cta: "Comprar tudo",
  products: [
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/s516drc8_WhatsApp%20Image%202026-05-14%20at%2000.40.49.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/8549u3dz_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2818%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/zu2068bg_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2817%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/9qr12hr0_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2816%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/h4kkvoxu_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2815%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/ykifu7re_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2814%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/l6dni0ja_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2813%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/nakvuko6_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2812%29.jpeg" },
  ],
};

export const banner = {
  kicker: "FRAGRÂNCIAS INTENSAS",
  titleLine1: "Para",
  titleItalic: "marcar",
  titleLine2: "presença",
  description: "Composições com âmbar, oud e baunilha. Inspiradas no Oriente Médio para criar memórias inesquecíveis.",
  cta: "Comprar",
  image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/ielqruif_ChatGPT%20Image%2012_05_2026%2C%2020_47_33.png",
};

export const feminine = {
  kicker: "ELEGÂNCIA",
  titleLine1: "Para",
  titleItalic: "Ela",
  description: "Fragrâncias delicadas e envolventes para momentos especiais.",
  products: [
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/prha5iqa_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2811%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/ojzgpuqa_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2810%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/wnqnywbx_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2810%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/yrv2zmqc_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%289%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/sytperqt_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%288%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/4k7jamys_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%287%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/e7w47bzr_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%286%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/fthrbyr7_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%285%29.jpeg" },
  ],
};

export const masculine = {
  kicker: "PARA ELE",
  titleLine1: "Para",
  titleItalic: "ele",
  description: "Fragrâncias masculinas com presença marcante. Madeira, especiarias e couro.",
  products: [
    {
      id: 0,
      name: "Lattafa The Kingdom Man 100ml",
      price: "41,92 €",
      image: "/images/Lattafa - The Kingdom (For Men).png",
      hoverImage: "/images/Lattafa - The Kingdom (For Men).png",
      brandLogo: "/images/logolattafa.png",
      tagline: "A elegância do Oriente Médio",
      fullDescription: "Descubra a essência da elegância e sofisticação com o The Kingdom EDP Spray for Men da Lattafa.",
      fragranceType: "Amber Fougere",
      bestFor: "Uso diário e ocasiões especiais",
      launchYear: "2024",
      inspiration: "Fragrância original Lattafa",
      notes: { topo: "Sálvia, Lavanda, Menta", coracao: "Tabaco, Baunilha, Flor de Laranjeira", base: "Benjoim, Fava Tonka, Ládano" },
      sizes: [{ size: "100ml", price: 41.92 }],
      sku: "6291108735428", ean: "6291108735428", rating: 4, reviews: 3
    },
    {
      id: 1,
      name: "French Avenue Spectre Ghost 80ml",
      price: "54,05 €",
      image: "/images/French Avenue - Spectre Ghost.png",
      hoverImage: "/images/French Avenue - Spectre Ghost.png",
      brandLogo: null,
      tagline: "Intensidade e Elegância",
      fullDescription: "French Avenue Spectre Ghost Eau de Parfum Masculino – Intensidade e Elegância em Cada Nota.",
      fragranceType: "Oriental Amadeirado Especiado",
      bestFor: "Uso diário e ocasiões especiais",
      launchYear: "2024",
      inspiration: "Fragrância original French Avenue",
      notes: { topo: "Bergamota, Gengibre, Cardamomo", coracao: "Rosa, Groselha Negra, Pimenta Rosa", base: "Patchouli, Madeira de Cedro, Baunilha" },
      sizes: [{ size: "80ml", price: 54.05 }],
      sku: "6291108735429", ean: "6291108735429", rating: 5, reviews: 1
    },
    {
      id: 2,
      name: "Lattafa Khamrah 100ml",
      price: "45,17 €",
      image: "/images/Lattafa - Khamrah.png",
      hoverImage: "/images/Lattafa - Khamrah.png",
      brandLogo: "/images/logolattafa.png",
      tagline: "O fascínio oriental",
      fullDescription: "Desvende a essência do fascínio oriental com LATTAFA Khamrah EDP.",
      fragranceType: "Aromática Picante",
      bestFor: "Uso diurno e noturno",
      launchYear: "2022",
      inspiration: "Fragrância original Lattafa",
      notes: { topo: "Canela, Noz-moscada, Bergamota", coracao: "Tâmaras, Praliné, Tuberosa, Mahonial", base: "Baunilha, Fava Tonka, Benjoim, Mirra, Âmbar, Akigalawood" },
      sizes: [{ size: "100ml", price: 45.17 }],
      sku: "6291108735430", ean: "6291108735430", rating: 0, reviews: 0
    },
    {
      id: 3,
      name: "Lattafa Asad Zanzibar 100ml",
      price: "27,06 €",
      image: "/images/Lattafa - Asad Zanzibar.png",
      hoverImage: "/images/Lattafa - Asad Zanzibar.png",
      brandLogo: "/images/logolattafa.png",
      tagline: "Exótico e sofisticado",
      fullDescription: "Lattafa Asad ZANZIBAR Man 100ml é uma fragrância masculina que incorpora a essência do exótico.",
      fragranceType: "Fresca Amadeirada",
      bestFor: "Dias quentes e ocasiões casuais",
      launchYear: "2024",
      inspiration: "Semelhante a 40 Knots de Xerjoff",
      notes: { topo: "Lavanda, Pimenta Preta", coracao: "Água de Coco, Íris, Sal", base: "Baunilha, Incenso" },
      sizes: [{ size: "100ml", price: 27.06 }],
      sku: "6291108735431", ean: "6291108735431", rating: 5, reviews: 1
    },
    {
      id: 4,
      name: "Lattafa Asad Man 100ml",
      price: "32,90 €",
      image: "/images/Lattafa - Asad.png",
      hoverImage: "/images/Lattafa - Asad.png",
      brandLogo: "/images/logolattafa.png",
      tagline: "Revele a sua força",
      fullDescription: "Lattafa Asad Man Eau de Parfum 100ml ajuda a revelar a masculinidade.",
      fragranceType: "Gourmet Picante",
      bestFor: "Tempo frio",
      launchYear: "2021",
      inspiration: "Inspirado em Sauvage Elixir (Dior)",
      notes: { topo: "Pimenta Negra, Tabaco, Abacaxi", coracao: "Patchouli, Café, Íris", base: "Baunilha, Âmbar, Madeira seca, Benjoim, Ládano" },
      sizes: [{ size: "100ml", price: 32.90 }],
      sku: "6291108735411", ean: "6291108735411", rating: 4, reviews: 9
    },
    {
      id: 5,
      name: "Lattafa Asad Bourbon 100ml",
      price: "37,12 €",
      image: "/images/Lattafa - Asad Bourbon.png",
      hoverImage: "/images/Lattafa - Asad Bourbon.png",
      brandLogo: "/images/logolattafa.png",
      tagline: "Intensidade e sofisticação",
      fullDescription: "Lattafa Asad Bourbon – Perfume Masculino 100ml - Intensidade e Sofisticação.",
      fragranceType: "Amadeirado Gourmand",
      bestFor: "Noites especiais e ocasiões marcantes",
      launchYear: "2024",
      inspiration: "Edição amadeirada gourmand premium",
      notes: { topo: "Canela, Pimenta Preta, Tabaco", coracao: "Baunilha, Oud, Âmbar", base: "Fava Tonka, Couro, Patchouli" },
      sizes: [{ size: "100ml", price: 37.12 }],
      sku: "6290362340362", ean: "6290362340362", rating: 5, reviews: 7
    },
    {
      id: 6,
      name: "Armaf Club de Nuit Intense Man",
      price: "49,90 €",
      image: "/images/Armaf - Club de Nuit Intense Man.png",
      hoverImage: "/images/Armaf - Club de Nuit Intense Man.png",
      brandLogo: null,
      tagline: "O clássico moderno",
      fullDescription: "Armaf Club de Nuit Intense Man é uma fragrância que se tornou um clássico moderno.",
      fragranceType: "Cítrico Amadeirado",
      bestFor: "Uso diário e noturno",
      launchYear: "2015",
      inspiration: "Inspirado em Creed Aventus",
      notes: { topo: "Limão, Maçã Verde, Bergamota", coracao: "Jasmin, Rosa, Pimenta", base: "Âmbar, Patchouli, Musgo, Baunilha" },
      sizes: [{ size: "105ml", price: 49.90 }],
      sku: "6291108735432", ean: "6291108735432", rating: 5, reviews: 12
    },
    {
      id: 7,
      name: "Fakhar Black",
      price: "29,90 €",
      image: "/images/Fakhar_Black.png",
      hoverImage: "/images/Fakhar_Black1.png",
      brandLogo: "/images/logolattafa.png",
      tagline: "Elegância contemporânea",
      fullDescription: "Fakhar Black é uma fragrância que combina frescor cítrico com notas amadeiradas e picantes.",
      fragranceType: "Aromático Fougere",
      bestFor: "Uso diário",
      launchYear: "2020",
      inspiration: "Inspirado em YSL Y",
      notes: { topo: "Gengibre, Maçã, Bergamota", coracao: "Lavanda, Gerânio, Sálvia", base: "Cedro, Âmbar, Patchouli" },
      sizes: [{ size: "100ml", price: 29.90 }],
      sku: "6291108735433", ean: "6291108735433", rating: 4, reviews: 15
    },
    {
      id: 8,
      name: "Lattafa Fakhar Black 100ml",
      price: "32,90 €",
      image: "/images/Lattafa_Fakhar_Black.png",
      hoverImage: "/images/Lattafa_Fakhar_Black.png",
      brandLogo: "/images/logolattafa.png",
      tagline: "Elegância e sofisticação",
      fullDescription: "Lattafa Fakhar Black é uma fragrância que combina frescor cítrico com notas amadeiradas e picantes.",
      fragranceType: "Aromático Fougere",
      bestFor: "Uso diário",
      launchYear: "2020",
      inspiration: "Inspirado em YSL Y",
      notes: { topo: "Gengibre, Maçã, Bergamota", coracao: "Lavanda, Gerânio, Sálvia", base: "Cedro, Âmbar, Patchouli" },
      sizes: [{ size: "100ml", price: 32.90 }],
      sku: "6291108735434", ean: "6291108735434", rating: 4, reviews: 10
    },
    {
      id: 9,
      name: "Afnan 9 PM Eau de Parfum 100ml",
      price: "43,39 €",
      image: "/images/Afnan_9PM_1.png",
      hoverImage: "/images/Afnan_9PM_2.png",
      brandLogo: null,
      tagline: "O fascínio cativante do âmbar e baunilha",
      fullDescription: "Experimente o fascínio cativante do 9PM da Afnan.",
      fragranceType: "Âmbar Baunilha",
      bestFor: "Uso diário, ocasiões casuais e formais",
      launchYear: "2020",
      inspiration: "Fragrância original Afnan",
      notes: { topo: "Maçã, Canela, Lavanda Selvagem, Bergamota", coracao: "Flor de Laranjeira, Lírio-do-Vale", base: "Baunilha, Fava Tonka, Âmbar, Patchouli" },
      sizes: [{ size: "100ml", price: 43.39 }],
      sku: "6290171002338", ean: "6290171002338", rating: 5, reviews: 1
    },
    {
      id: 10,
      name: "Lattafa Nebras Unissex 100ml",
      price: "35,67 €",
      oldPrice: "39,63 €",
      discount: "10%",
      image: "/images/Lattafa_Nebras_1.png",
      hoverImage: "/images/Lattafa_Nebras_2.png",
      brandLogo: "/images/logolattafa.png",
      tagline: "Obra-prima olfativa oriental gourmand",
      fullDescription: "O Lattafa Pride Nebras Eau de Parfum é uma verdadeira obra-prima olfativa.",
      fragranceType: "Oriental Gourmand",
      bestFor: "Homens e mulheres que desejam destacar-se",
      launchYear: "2022",
      inspiration: "Fragrância original Lattafa",
      notes: { topo: "Bagas vermelhas, Tangerina", coracao: "Baunilha, Raiz do cacau, Rosa", base: "Cumaru, Âmbar, Almíscar, Açúcar" },
      sizes: [{ size: "100ml", price: 35.67 }],
      sku: "6291108735435", ean: "6291108735435", rating: 0, reviews: 0
    },
    {
      id: 11,
      name: "Lattafa Asad Elixir 100ml",
      price: "45,01 €",
      image: "/images/Lattafa_Asad_Elixir_1.png",
      hoverImage: "/images/Lattafa_Asad_Elixir_2.png",
      brandLogo: "/images/logolattafa.png",
      tagline: "A expressão máxima do poder masculino",
      fullDescription: "Lattafa Asad Elixir - a expressão máxima do poder masculino.",
      fragranceType: "Oriental Amadeirado",
      bestFor: "Dias frios, noites elegantes",
      launchYear: "2024",
      inspiration: "Fragrância original Lattafa",
      notes: { topo: "Pimenta Rosa, Açafrão, Toranja", coracao: "Madeira de Cedro, Nicotiana, Baunilha", base: "Cashmeran, Olíbano, Patchouli, Âmbar" },
      sizes: [{ size: "100ml", price: 45.01 }],
      sku: "6291108735436", ean: "6291108735436", rating: 5, reviews: 2
    },
    {
      id: 12,
      name: "Armaf Club De Nuit Lionheart Man 100ml",
      price: "70,18 €",
      image: "/images/Armaf_Lionheart_1.png",
      hoverImage: "/images/Armaf_Lionheart_2.png",
      brandLogo: null,
      tagline: "A força e a elegância em uma fragrância única",
      fullDescription: "Club De Nuit Lionheart Man – A Força e a Elegância.",
      fragranceType: "Oriental Fougère",
      bestFor: "Homens confiantes",
      launchYear: "2025",
      inspiration: "Fragrância original Armaf",
      notes: { topo: "Hortelã, Lavanda", coracao: "Benjoim, Baunilha", base: "Tabaco, Mel, Fava Tonka" },
      sizes: [{ size: "100ml", price: 70.18 }],
      sku: "6291108735437", ean: "6291108735437", rating: 5, reviews: 1
    },
    {
      id: 13,
      name: "Lattafa His Confession 100ml",
      price: "51,59 €",
      image: "/images/Lattafa_His_Confession_1.png",
      hoverImage: "/images/Lattafa_His_Confession_2.png",
      brandLogo: "/images/logolattafa.png",
      tagline: "A fragrância definitiva para o homem moderno",
      fullDescription: "His Confession da Lattafa – fragrância para o homem moderno.",
      fragranceType: "Amadeirado e Âmbar",
      bestFor: "Reuniões de negócios a jantares especiais",
      launchYear: "2024",
      inspiration: "Fragrância original Lattafa",
      notes: { topo: "Canela, Lavanda, Tangerina", coracao: "Benjoim, Íris, Cipreste, Mahonial", base: "Baunilha, Tonka, Incenso, Cedro, Âmbar, Patchouli" },
      sizes: [{ size: "100ml", price: 51.59 }],
      sku: "6291108735438", ean: "6291108735438", rating: 0, reviews: 0
    },
    {
      id: 14,
      name: "Lattafa Bade'e Al Oud Amethyst 100ml",
      price: "59,90 €",
      image: "/images/Lattafa_Amethyst_1.png",
      hoverImage: "/images/Lattafa_Amethyst_2.png",
      brandLogo: "/images/logolattafa.png",
      tagline: "O poder da sensualidade e sofisticação",
      fullDescription: "Descubra o poder da sensualidade com Lattafa Badee Al Oud Amethyst.",
      fragranceType: "Oriental Floral Intenso",
      bestFor: "Noites especiais e estações frias",
      launchYear: "2023",
      inspiration: "Fragrância original Lattafa",
      notes: { topo: "Pimenta rosa, Bergamota", coracao: "Rosa da Turquia, Rosa búlgara, Jasmim", base: "Oud, Âmbar, Baunilha" },
      sizes: [{ size: "100ml", price: 59.90 }],
      sku: "6291108735439", ean: "6291108735439", rating: 0, reviews: 0
    },
    {
      id: 15,
      name: "Afnan Supremacy Collector's Edition 100ml",
      price: "89,90 €",
      image: "/images/Afnan_Supremacy_1.png",
      hoverImage: "/images/Afnan_Supremacy_2.png",
      brandLogo: null,
      tagline: "Homenagem à elegância masculina",
      fullDescription: "O Afnan Supremacy Collector's Edition é uma homenagem à elegância masculina.",
      fragranceType: "Frutado - Couro - Amadeirado",
      bestFor: "Eventos formais, noites especiais",
      launchYear: "2024",
      inspiration: "Fragrância original Afnan",
      notes: { topo: "Ananás, Bergamota, Maçã, Flores brancas", coracao: "Flor de laranjeira, Bétula, Âmbar", base: "Musgo de carvalho, Almíscar, Ambroxan" },
      sizes: [{ size: "100ml", price: 89.90 }],
      sku: "6291108735440", ean: "6291108735440", rating: 0, reviews: 0
    },
    {
      id: 16,
      name: "Armaf Club De Nuit Urban Man Elixir 105ml",
      price: "51,76 €",
      image: "/images/Armaf_Urban_Elixir_1.png",
      hoverImage: "/images/Armaf_Urban_Elixir_2.png",
      brandLogo: null,
      tagline: "A essência da masculinidade moderna",
      fullDescription: "Armaf Club De Nuit Urban Man Elixir – A Essência da Masculinidade Moderna.",
      fragranceType: "Cítrico Aromático Especiado",
      bestFor: "Dia a dia e ocasiões especiais",
      launchYear: "2024",
      inspiration: "Fragrância original Armaf",
      notes: { topo: "Bergamota, Jasmim, Flor de Laranjeira, Pimenta Rosa", coracao: "Lavanda, Gerânio, Elemi, Vetiver, Açafrão", base: "Âmbar, Patchouli, Cedro, Labdanum" },
      sizes: [{ size: "105ml", price: 51.76 }],
      sku: "6291108735441", ean: "6291108735441", rating: 0, reviews: 0
    },
    {
      id: 17,
      name: "Lattafa Khamrah Dukhan Unissex 100ml",
      price: "46,74 €",
      image: "/images/Lattafa_Khamrah_Dukhan_1.png",
      hoverImage: "/images/Lattafa_Khamrah_Dukhan_2.png",
      brandLogo: "/images/logolattafa.png",
      tagline: "Perfume oriental unissex intenso",
      fullDescription: "Khamrah Dukhan da Lattafa – Perfume Oriental Unissex Intenso.",
      fragranceType: "Oriental Amadeirado Especiado",
      bestFor: "Noites especiais",
      launchYear: "2025",
      inspiration: "Fragrância original Lattafa",
      notes: { topo: "Pimenta, Tangerina, Especiarias", coracao: "Incenso, Patchouli, Ladano, Flor de Laranjeira", base: "Praliné, Âmbar, Fava Tonka, Tabaco, Benjoim" },
      sizes: [{ size: "100ml", price: 46.74 }],
      sku: "6291108735442", ean: "6291108735442", rating: 0, reviews: 0
    },
    {
      id: 18,
      name: "Lattafa Maahir Black Edition 100ml",
      price: "37,74 €",
      image: "/images/Maahir_Black_1.png",
      hoverImage: "/images/Maahir_Black_2.png",
      brandLogo: "/images/logolattafa.png",
      tagline: "Fragrância oriental intensa",
      fullDescription: "MAAHIR BLACK EDITION - fragrância oriental com notas intensas.",
      fragranceType: "Oriental Amadeirado",
      bestFor: "Homens elegantes",
      launchYear: "2024",
      inspiration: "Inspirado em Encre Noire à l'Extrême",
      notes: { topo: "Pimenta Rosa, Pimenta Preta, Açafrão", coracao: "Ruibarbo, Cade, Ládano, Bálsamo", base: "Couro, Cedro, Patchouli, Guaiac, Almíscar, Musgo" },
      sizes: [{ size: "100ml", price: 37.74 }],
      sku: "6291108735443", ean: "6291108735443", rating: 0, reviews: 0
    },
    {
      id: 19,
      name: "Maison Alhambra Salvo Elixir 60ml",
      price: "25,19 €",
      image: "/images/Salvo_Elixir_1.png",
      hoverImage: "/images/Salvo_Elixir_2.png",
      brandLogo: null,
      tagline: "Fragrância oriental fougère",
      fullDescription: "Salvo Elixir - fragrância oriental fougère masculina.",
      fragranceType: "Oriental Fougère",
      bestFor: "Uso noturno",
      launchYear: "2022",
      inspiration: "Inspirado em Dior Sauvage Elixir",
      notes: { topo: "Pimenta Preta, Tabaco, Abacaxi", coracao: "Patchouli, Íris, Café", base: "Amadeiradas, Baunilha, Âmbar, Benjoim, Ládano" },
      sizes: [{ size: "60ml", price: 25.19 }],
      sku: "6291108735444", ean: "6291108735444", rating: 0, reviews: 0
    },
    {
      id: 20,
      name: "Lattafa Musamam Black Intense 100ml",
      price: "59,90 €",
      image: "/images/Musamam_Black_Intense_1.png",
      hoverImage: "/images/Musamam_Black_Intense_2.png",
      brandLogo: "/images/logolattafa.png",
      tagline: "Fragrância amadeirada intensa",
      fullDescription: "Musamam Black Intense - fragrância amadeirada aromática.",
      fragranceType: "Amadeirado Aromático",
      bestFor: "Uso noturno",
      launchYear: "2025",
      inspiration: "Fragrância original Lattafa",
      notes: { topo: "Sálvia, Lavanda, Noz-moscada, Bergamota", coracao: "Rosácea, Gerânio, Cedro, Mahonia", base: "Coco, Fava Tonka, Bordo, Ambrofix, Patchouli" },
      sizes: [{ size: "100ml", price: 59.90 }],
      sku: "6291108735445", ean: "6291108735445", rating: 5, reviews: 2
    },
    {
      id: 21,
      name: "Lattafa Ishq Al Shuyukh Silver 100ml",
      price: "49,90 €",
      image: "/images/Ishq_Al_Shuyukh_Silver_1.png",
      hoverImage: "/images/Ishq_Al_Shuyukh_Silver_2.png",
      brandLogo: "/images/logolattafa.png",
      tagline: "Autenticidade e sofisticação",
      fullDescription: "Lattafa Pride Ishq Al Shuyukh Silver – A Essência da Autenticidade.",
      fragranceType: "Cítrica, Oriental, Amadeirada",
      bestFor: "Dia a dia elegante",
      launchYear: "2024",
      inspiration: "Fragrância original Lattafa",
      notes: { topo: "Limão, Bergamota", coracao: "Pimenta Preta, Ananás", base: "Madeira âmbar, Cedro, Patchouli, Baunilha" },
      sizes: [{ size: "100ml", price: 49.90 }],
      sku: "6291108735446", ean: "6291108735446", rating: 0, reviews: 0
    },
    {
      id: 22,
      name: "Niche Emarati Mughal Fort 100ml",
      price: "59,90 €",
      image: "/images/Mughal_Fort_1.png",
      hoverImage: "/images/Mughal_Fort_2.png",
      brandLogo: "/images/logolattafa.png",
      tagline: "Luxo, intensidade e sofisticação",
      fullDescription: "Mughal Fort - luxo, intensidade e sofisticação.",
      fragranceType: "Oriental doce amadeirada",
      bestFor: "Quem valoriza perfumes marcantes",
      launchYear: "2024",
      inspiration: "Dupe de Minuit et Demi",
      notes: { topo: "Cardamomo, Pimenta", coracao: "Caramelo, Cedro", base: "Baunilha, Âmbar, Almíscar" },
      sizes: [{ size: "100ml", price: 59.90 }],
      sku: "6291108735447", ean: "6291108735447", rating: 0, reviews: 0
    },
    {
      id: 23,
      name: "Maison Alhambra Cassius 100ml",
      price: "23,35 €",
      image: "/images/Cassius_1.png",
      hoverImage: "/images/Cassius_2.png",
      brandLogo: null,
      tagline: "Essência floral frutada",
      fullDescription: "Cassius da Maison Alhambra - fragrância Floral Fruity.",
      fragranceType: "Floral Frutada",
      bestFor: "Uso diário",
      launchYear: "2022",
      inspiration: "Fragrância original",
      notes: { topo: "Noz-moscada, Maçã Verde", coracao: "Fava Tonka, Rosa", base: "Patchouli, Baunilha" },
      sizes: [{ size: "100ml", price: 23.35 }],
      sku: "6291108735448", ean: "6291108735448", rating: 0, reviews: 0,
      outOfStock: true
    },
    {
      id: 24,
      name: "Armaf Club de Nuit Sillage 105ml",
      price: "55,90 €",
      image: "/images/Armaf_Sillage_1.png",
      hoverImage: "/images/Armaf_Sillage_2.png",
      brandLogo: null,
      tagline: "Fragrância fresca e elegante",
      fullDescription: "Armaf Club de Nuit Sillage - fragrância fresca e elegante.",
      fragranceType: "Fresco Amadeirado",
      bestFor: "Uso diário",
      launchYear: "2024",
      inspiration: "Fragrância original Armaf",
      notes: { topo: "Limão, Bergamota, Maçã Verde", coracao: "Jasmim, Rosa, Pimenta Rosa", base: "Âmbar, Almíscar, Cedro" },
      sizes: [{ size: "105ml", price: 55.90 }],
      sku: "6291108735449", ean: "6291108735449", rating: 0, reviews: 0
    }
  ]
};

export const trends = {
  kicker: "NÃO FIQUE SEM",
  titleLine1: "Últimas",
  titleItalic: "tendências",
  products: [
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/h4kkvoxu_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2815%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/ykifu7re_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2814%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/l6dni0ja_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2813%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/nakvuko6_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2812%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/prha5iqa_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2811%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/ojzgpuqa_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2810%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/vjhmq6t8_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%284%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/b25on144_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%283%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/nzrpu01i_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%282%29.jpeg" },
    { image: "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/7ekqnmcw_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%281%29.jpeg" },
  ],
};

export const follow = {
  kicker: "Siga-nos",
  handle: "@noraya.perfumes",
  gallery: [
    "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/s516drc8_WhatsApp%20Image%202026-05-14%20at%2000.40.49.jpeg",
    "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/8549u3dz_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2818%29.jpeg",
    "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/zu2068bg_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2817%29.jpeg",
    "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/9qr12hr0_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2816%29.jpeg",
    "https://customer-assets.emergentagent.com/job_content-builder-115/artifacts/h4kkvoxu_WhatsApp%20Image%202026-05-14%20at%2000.40.49%20%2815%29.jpeg",
  ],
};

export const newsletter = {
  titleLine1: "Está",
  titleItalic: "na lista?",
  description: "Receba lançamentos, ofertas exclusivas e novidades sobre as fragrâncias árabes mais desejadas.",
  placeholder: "O seu melhor e-mail",
  cta: "Inscrever",
};

export const footer = {
  columns: [
    { title: "LOJA", links: ["Ver tudo", "Novidades", "Mais vendidos", "Para Ela", "Para Ele"] },
    { title: "AJUDA", links: ["Portes e entregas", "Trocas e devoluções", "FAQ", "Fale connosco"] },
    { title: "INSTITUCIONAL", links: ["Sobre a Noraya", "Política de privacidade", "Termos de uso"] },
  ],
  copyright: "© 2026 NORAYA — Perfumes Árabes. Todos os direitos reservados.",
};
